# Generated by Django 2.2.7 on 2019-12-01 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('link', models.CharField(max_length=256, unique=True)),
                ('company', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=20)),
                ('createAt', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keywords', models.CharField(max_length=128)),
                ('remote', models.BooleanField()),
                ('location', models.CharField(max_length=128)),
                ('skill', models.BooleanField()),
                ('employment_type', models.CharField(choices=[('NO', 'none'), ('FULL', 'Полная занятость'), ('PARTIAL', 'Частичная занятость'), ('TEMPORARY', 'Временная работа'), ('INTERN', 'Стажировка')], default='NO', max_length=9)),
                ('schedule_work', models.CharField(choices=[('NO', 'none'), ('FULL', 'Полный день'), ('SHIFT', 'Сменный график'), ('FLEX', 'Гибкий график'), ('REMOTE', 'Вахтовый метод')], default='NO', max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
