# Generated by Django 2.2.7 on 2019-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindJob', '0002_question_createat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='employment_type',
            field=models.CharField(choices=[('NO', 'Не знаю'), ('FULL', 'Полная занятость'), ('PARTIAL', 'Частичная занятость'), ('TEMPORARY', 'Временная работа'), ('INTERN', 'Стажировка')], default='NO', max_length=9),
        ),
        migrations.AlterField(
            model_name='question',
            name='keywords',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='schedule_work',
            field=models.CharField(choices=[('NO', 'Не знаю'), ('FULL', 'Полный день'), ('SHIFT', 'Сменный график'), ('FLEX', 'Гибкий график'), ('REMOTE', 'Вахтовый метод')], default='NO', max_length=9),
        ),
    ]
