# Generated by Django 2.2.7 on 2019-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindJob', '0004_auto_20191205_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='keywords',
            field=models.CharField(max_length=128),
        ),
    ]
