# Generated by Django 2.2.7 on 2019-12-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindJob', '0005_auto_20191208_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='location',
        ),
        migrations.RemoveField(
            model_name='question',
            name='remote',
        ),
    ]
